data:
  feature: Sentence
  label: Sentiment
mlflow:
  experiment_name: Experiment_7
  model_name: sentiment_classifier
  model_uri: null
  tracking_uri: http://ec2-3-7-73-210.ap-south-1.compute.amazonaws.com:5000
s3:
  bucket: sentimet-analysis
  save_object: cleaned-data/data.csv
  train_object: training-data/train.csv
